### ISSUE TITLE
snmp.table not returning values for Counter64 entries

### ISSUE THREAD

**Issue by skuchuk** [stephenwvickers/node-net-snmp#20]
I am faced with an issue of reading large Counter64 values using snmp.table.
I found the following description in the documentation:
"Since JavaScript does not offer full 64 bit integer support objects with type Counter64 cannot be supported in the same way as other integer types, instead Node.js Buffer objects are used. Users are responsible for producing (i.e. for set() requests) and consuming (i.e. the varbinds passed to callback functions) Buffer objects. That is, this module does not work with 64 bit integers, it simply treats them as opaque Buffer objects."

Printing the table I receive after calling snmp.table I can see all the entries in the table other than the two I need.
That is, they are not represented as a Buffer like the documentation suggests rather they are missing altogether from the response.
using snmptable from a shell window I can see the entire table including the entries I need.
For reference, the values I am trying to read are 1730433156953 and 387069230443.

I am using an Ubuntu 16.04 LTS machine with node v4.4.7 and net-snmp package v1.1.19

Any ideas?

**Comment by stephenwvickers** [comment]
What SNMP version are you using?

Can you provide an example program that fails?

**Comment by guigons** [comment]
I have de same problem. I'd like to use net-snmp for cisco equipment implementations but it dosen't work just for Counter64. Following a simple example about this problem (I'm using 2c snmp version)

** Works perfectly:
# node teste-get.js rdistcta1 public 2c 1.3.6.1.2.1.31.1.1.1.1.15
1.3.6.1.2.1.31.1.1.1.1.15|GigabitEthernet0/6/0/0

** Problem with Counter64 OID
# node teste-get.js rdistcta1 public 2c 1.3.6.1.2.1.31.1.1.1.10.15
1.3.6.1.2.1.31.1.1.1.10.15|��<Է�

For network implementations use Counter64 is required, because we work with TenGiga or HundredGiga interfaces. So Counter32 isn't enough. 

Thanks a lot!

Script used:

// Copyright 2013 Stephen Vickers

var snmp = require ("net-snmp");

if (process.argv.length < 6) {
	console.log ("usage: snmp-get <target> <community> <version> <oid>");
	process.exit (1);
}

var target = process.argv[2];
var community = process.argv[3];
var version = (process.argv[4] == "2c") ? snmp.Version2c : snmp.Version1;

var oids = [process.argv[5]];

var session = snmp.createSession (target, community, {version: version});

session.get (oids, function (error, varbinds) {
	if (error) {
		console.error (error.toString ());
	} else {
		for (var i = 0; i < varbinds.length; i++) {
			if (snmp.isVarbindError (varbinds[i]))
				console.error (snmp.varbindError (varbinds[i]));
			else
				console.log (varbinds[i].oid + "|" + varbinds[i].value);
		}
	}
});

**Comment by stephenwvickers** [comment]
@guigons I am not sure I understand your issue.

This library provides access to Counter64 values by way of a Node Buffer object, as detailed in the docs.

You simply use that and work with another Node library to manipulate, use, or convert the value to a string format, for example using the int64-buffer module (I am not suggesting you specifically use this one, it's just the first one I came across on my searches):

```javascript
var Uint64BE = require("int64-buffer").Uint64BE

var value = new Uint64BE(varbinds[i].value)

console.log(varbinds[i].oid + "|" + value.toNumber())
```
